### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by Hasimir** [BTCMarkets/API#2] opened 2014-10-18 08:12 UTC
What are the undocumented error codes in this API?

A response like this:

``` json
{"success":false,"errorCode":5,"errorMessage":" error occured while trying to get balance."}
```

Is effectively useless when attempting to debug something.

**Comment by Hasimir** [comment] 2014-10-18 08:17
Note: I get a "bad request" HTML error when deliberately introducing errors in the authentication method to try to induce a different API error message, so it is unclear as to whether this is an authentication failure or some other type of failure.

**Comment by JarrodCrane** [comment] 2014-10-20 11:27
Hi Ben,

We can see the error you are getting is due to the timestamp format being invalid. 

It should be in the format 1413618968669 but is coming through as the format 1413618968669.7048. We will look into improving the error messages as they are quite vague.

**Comment by Hasimir** [comment] 2014-10-20 16:55
Interesting, because rounding it off generally produced something else and deliberately inducing an authentication failure through a browser produced a different message.  Specifically this one:

``` json
{"success":false,"errorCode":1,"errorMessage":"Authentication failed."}
```

Yeah, I started keeping track.  And yes, I knew one of the recent ones used the floating point.  Basically I'm using time.time() in Python 3, which produces a floating point of the number of seconds since the epoch to six decimal places.  To make that milliseconds it gets multiplied by 1,000 and then it's just a matter of encasing it in round(), int() or leaving it as is.  I'll go back to one of the other two methods and see what happens.

**Comment by Hasimir** [comment] 2014-10-20 18:20
**Sigh** ...

I hope you're not too attached to that API developer you used ... it might be necessary to beat him to a pulp with the HMAC RFCs ...

So, the signature format does not match either of the two formats cited in the RFCs (digest or hex digest).  What I've been transmitting was the digest of the signature.  The expected format in the documentation uses some form of encoding, something like uuencoding or base 64 encoding.  A good example of the latter is the ASCII armouring in an OpenPGP key or message.  The problem is that there are many encoding formats which produce output similar to that and your API developer (Martin something, IIRC) didn't document which format he used.  Actually he didn't really document much of anything.

Which means it's time to trawl through the source code or do unpleasant things to Martin.  Why he didn't just go for a hex digest I do not know, but maybe he thought he was being clever or something.

Oh, by the way, I have tried base64 itself, no luck there.  Still, there are many, many forms of encoding so finding out which one it is and what twist has been put on it would be a good thing.  Ideally getting a look at the part of the API which verifies the signature would be good (if it's really secure then that shouldn't be a problem).

**Comment by Hasimir** [comment] 2014-10-20 19:17
It looks like the same API has been sold to a South African exchange, but this time some sample code for client connections has been written.  What passes for [documentation](https://github.com/ICE3X/api-doc) is the same (i.e. almost entirely useless when it comes to authentication), but this time there's a [node.js client](https://github.com/ICE3X/api-client-nodejs), a [Go language client](https://github.com/ICE3X/api-client-go) and the beginning of what might one day be a [Java client](https://github.com/ICE3X/api-client-java).

There's enough information in those clients to realise that there is a _lot_ more that is undocumented than I realised.  For example, the Go client, if I'm reading that source correctly, does use base64 encoding, but first it **decodes** the secret key, performs various functions and then re-encodes the signature.  I'm not yet sure what other requirements are buried in there since that's the first bit of Go I've really looked at and I'm not sure what all its modules do yet.  So I'm still not sure whether it uses standard base64 or "URL safe" base64 or if there's something else going on.

I also don't know if these sample clients actually work or if they've undergone any testing at all.  I'd be inclined to suspect about the same degree of diligence has gone into testing as went into the documentation.

**Comment by JarrodCrane** [comment] 2014-10-21 00:04
Hi Ben,

I can confirm that the secret key is standard Base64 encoded and thus needs to be decoded. The final signature is then standard Base64 encoded.

We have many clients currently using the API but we know the documentation is incomplete. We are in the middle of revamping it (as well as providing more sample code).

I have emailed you a complete Java code sample.

**Comment by Hasimir** [comment] 2014-10-29 10:06
> I can confirm that the secret key is standard Base64 encoded and thus needs to be decoded. The final signature is then standard Base64 encoded.
> 
> We have many clients currently using the API but we know the documentation is incomplete. We are in the middle of revamping it (as well as providing more sample code).
> 
> I have emailed you a complete Java code sample. 

Yeah, got it, thanks.

I've also been conferring with Martin and he discovered that the way Python handles JSON (as [dictionaries](https://docs.python.org/3.4/tutorial/datastructures.html#dictionaries) which sort via key).  Basically the API expects the POST data in a specific order, which the other languages used did, while Python assumes that the key is what is related to the value, not the order it appears in a URL.

I've still got a bit of testing to do, but at least this is revealing certain things to improve in ver. 2 of the API.  Not just the docs.

**Comment by JarrodCrane** [comment] 2017-07-04 05:56
Closing this issue as we have improved documentation and are currently working to improve it further.

**Closed as completed by JarrodCrane** 2017-07-04 05:56 UTC
