### ISSUE TITLE
Crypto Withdraw Validation Email

### ISSUE THREAD

**Issue by mercive** [BTCMarkets/API#114] opened 2018-02-11 08:18 UTC
Hi,

I raised the issue with BTCMarkets support and they directed me here to ask the question.

I'm integrating the Trading software with BTC API and would like to know if it is possible to disable Crypto Withdfraw email verification ? 
As normally, no needs for any email validations  if the wythdraw has been requested via API call.

I understand this has been done to increase the security, but it makes very hard for API integrations.

Is it possible to disable withdraw email verification for my account or for API calls, so I can complete the integration ? 

Thank you

**Comment by mercive** [comment] 2018-02-15 10:15
Hi, could anyone help ?

**Comment by justin-ngin** [comment] 2018-02-15 20:29
Hi @mercive ,

Sorry for the delayed response. I'm reaching out to the dev team for you. I'll let you know as soon as I find out.

Thanks,
Justin

**Comment by martin-nginio** [comment] 2019-11-05 01:16
this is a duplicate of this issue which is in our roadmap for this year:
https://github.com/BTCMarkets/API/issues/141

Thanks and closing this issue. 

Regards,
Martin

**Closed as completed by martin-nginio** 2019-11-05 01:16 UTC
