### ISSUE TITLE
Withdraw comes back with invalid authentication

### ISSUE THREAD

**Issue by splundge** [BTCMarkets/API#138] opened 2018-05-29 09:12 UTC
Hi
When I perform a withdrawal, it comes back with 'invalid authentication':
`{"success":false,"errorCode":1,"errorMessage":"Authentication failed."}`

I can create trades and check my balance perfectly fine, so my authentication must work.
Here's a sample HTTP POST request:

```
POST https://api.btcmarkets.net/fundtransfer/withdrawCrypto HTTP/1.1
User-Agent: Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0
Accept-Charset: UTF-8
Accept: application/json
apikey: (MY API KEY)
timestamp: 1526171453388
signature: (MY SIG)
Content-Type: application/json; charset=utf-8
Host: api.btcmarkets.net
Content-Length: 83
Expect: 100-continue
Connection: Keep-Alive

{"amount":10000000,"address":"(TARGET ADDRESS)","currency":"BTC"}
```

i am using c# and .net 4.7.1 to execute my withdraw request. What am I doing wrong?

**Comment by justin-ngin** [comment] 2018-05-29 16:57
I"m closing this as it's a duplicate of #135

**Closed as completed by justin-ngin** 2018-05-29 16:57 UTC
Labels: duplicate
